# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZWc14vm6xwyheUbKr1HKDOwqQx3MYMv

**TASK - 4**
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# Step 1: Load the analysed data and setup

# Path to the CSV file created in Task 3
file_path = "/content/drive/MyDrive/MiniProject1/Data/trends_analysed.csv"

# Load the analysed data
data = pd.read_csv(file_path)

# Create the output folder if it does not exist
output_folder = "/content/drive/MyDrive/MiniProject1/outputs"
os.makedirs(output_folder, exist_ok=True)

print("Data loaded successfully.")
print("Data shape:", data.shape)

# Step 2: Chart 1 - Top 10 Stories by Score

# Select the 10 stories with the highest scores
top_stories = data.nlargest(10, "score").copy()

# Shorten titles that are longer than 50 characters
top_stories["short_title"] = top_stories["title"].apply(
    lambda title: title[:50] + "..." if len(title) > 50 else title
)

# Create a horizontal bar chart
plt.figure(figsize=(10, 6))

plt.barh(
    top_stories["short_title"],
    top_stories["score"]
)

plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")

# Put the highest-scoring story at the top
plt.gca().invert_yaxis()

plt.tight_layout()

# Save the chart before displaying it
plt.savefig(
    f"{output_folder}/chart1_top_stories.png"
)

plt.show()

# Step 3: Chart 2 - Stories per Category

# Count the number of stories in each category
category_counts = data["category"].value_counts()

# Create a bar chart with a different colour for each bar
plt.figure(figsize=(9, 6))

plt.bar(
    category_counts.index,
    category_counts.values,
    color=["steelblue", "orange", "green", "red", "purple"]
)

plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.tight_layout()

# Save the chart before displaying it
plt.savefig(
    f"{output_folder}/chart2_categories.png"
)

plt.show()

# Step 4: Chart 3 - Score vs Comments

# Separate popular and non-popular stories
popular = data[data["is_popular"] == True]
not_popular = data[data["is_popular"] == False]

# Create the scatter plot
plt.figure(figsize=(10, 6))

# Plot non-popular stories
plt.scatter(
    not_popular["score"],
    not_popular["num_comments"],
    label="Not Popular"
)

# Plot popular stories
plt.scatter(
    popular["score"],
    popular["num_comments"],
    label="Popular"
)

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")

# Display the labels for the two groups
plt.legend()

plt.tight_layout()

# Save the chart before displaying it
plt.savefig(
    f"{output_folder}/chart3_scatter.png"
)

plt.show()

# Step 5: Create the TrendPulse Dashboard

# Create a 2 x 2 layout for the three charts
fig, axes = plt.subplots(
    2,
    2,
    figsize=(16, 10)
)

# Add the overall dashboard title
fig.suptitle(
    "TrendPulse Dashboard",
    fontsize=18
)

# Dashboard Chart 1

axes[0, 0].barh(
    top_stories["short_title"],
    top_stories["score"]
)

axes[0, 0].set_title("Top 10 Stories by Score")
axes[0, 0].set_xlabel("Score")
axes[0, 0].set_ylabel("Story Title")

# Put the highest score at the top
axes[0, 0].invert_yaxis()

# Dashboard Chart 2

axes[0, 1].bar(
    category_counts.index,
    category_counts.values,
    color=["steelblue", "orange", "green", "red", "purple"]
)

axes[0, 1].set_title("Stories per Category")
axes[0, 1].set_xlabel("Category")
axes[0, 1].set_ylabel("Number of Stories")


# Dashboard Chart 3

axes[1, 0].scatter(
    not_popular["score"],
    not_popular["num_comments"],
    label="Not Popular"
)

axes[1, 0].scatter(
    popular["score"],
    popular["num_comments"],
    label="Popular"
)

axes[1, 0].set_title("Score vs Comments")
axes[1, 0].set_xlabel("Score")
axes[1, 0].set_ylabel("Number of Comments")
axes[1, 0].legend()


# Hide the unused fourth subplot
axes[1, 1].axis("off")


# Adjust the layout
plt.tight_layout()

# Leave space for the dashboard title
plt.subplots_adjust(top=0.92)

# Save the complete dashboard
plt.savefig(
    f"{output_folder}/dashboard.png"
)

plt.show()


print("\nAll charts saved successfully.")
print(f"Output folder: {output_folder}")