# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4PSE0sQO9eCeziMf6uVn38QtdRnv0v_

**TASK - 2**
"""

import pandas as pd

# Step 1: Load the JSON file

# Path to the JSON file generated in Task 1
file_path = "/content/drive/MyDrive/MiniProject1/Data/trends_20260928.json"

# Load the JSON data into a Pandas DataFrame
data = pd.read_json(file_path)

# Print the number of rows loaded from the JSON file
print(f"Loaded {len(data)} stories")

# Display the first few rows to understand the data
print("\nFirst 5 rows:")
print(data.head())

# Step 2: Remove duplicate stories

# Check how many duplicate post_ids are present
duplicate_count = data.duplicated(subset="post_id").sum()

print(f"\nNumber of duplicate post_ids: {duplicate_count}")

# Remove duplicate stories based on post_id
data = data.drop_duplicates(subset="post_id")

print(f"After removing duplicates: {len(data)}")

# Step 3: Handle missing values

# Check the number of missing values in each column
print("\nMissing values per column:")
print(data.isnull().sum())

# Remove rows where post_id, title, or score is missing
data = data.dropna(
    subset=["post_id", "title", "score"]
)

print(f"\nAfter removing nulls: {len(data)}")


# Step 4: Convert data types

# Make sure score and num_comments are stored as integers
data["score"] = pd.to_numeric(
    data["score"],
    errors="coerce"
)

data["num_comments"] = pd.to_numeric(
    data["num_comments"],
    errors="coerce"
)

# Remove rows where numeric conversion resulted in missing values
data = data.dropna(
    subset=["score", "num_comments"]
)

# Convert the columns to integer type
data["score"] = data["score"].astype(int)
data["num_comments"] = data["num_comments"].astype(int)

print("\nData types after conversion:")
print(data[["score", "num_comments"]].dtypes)

# Step 5: Remove low-quality stories

# Keep only stories with a score of 5 or more
data = data[data["score"] >= 5]

print(f"\nAfter removing low-score stories: {len(data)}")

# Step 6: Remove extra whitespace from titles

# Remove leading and trailing spaces from story titles
data["title"] = data["title"].str.strip()

print("\nCleaned title whitespace.")

# Step 7: Save the cleaned data as CSV

output_path = "/content/drive/MyDrive/MiniProject1/Data/trends_clean.csv"

# Save the cleaned DataFrame as a CSV file
data.to_csv(
    output_path,
    index=False
)

print(f"\nSaved cleaned data with {len(data)} rows ")

# Step 8: Display stories per category

print("\nStories per category:")

category_counts = data["category"].value_counts()

print(category_counts)