# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oywxcX9oXwmwQSNjAhlB42rF8vlzC5Df

**TASK - 3**
"""

import pandas as pd
import numpy as np

# Step 1: Load and explore the cleaned data

# Path to the cleaned CSV file created in Task 2
file_path = "/content/drive/MyDrive/MiniProject1/Data/trends_clean.csv"

# Load the CSV file into a Pandas DataFrame
cleaned_original_data = pd.read_csv(file_path)

# Store the cleaned data in a working DataFrame
data = cleaned_original_data

# Display the first 5 rows of the DataFrame
print("First 5 rows:\n")
print(data.head())

# Display the number of rows and columns
print("\nData shape:", data.shape)

# Calculate the average score of all stories
average_score = data["score"].mean()

print(f"\nAverage score: {average_score:.2f}")

# Calculate the average number of comments
average_comments = data["num_comments"].mean()

print(f"Average comments: {average_comments:.2f}")

# Step 2: Calculate statistics using NumPy

# Convert the score column into a NumPy array
scores = data["score"].to_numpy()

# Calculate the mean score using NumPy
mean_scores = np.mean(scores)

# Calculate the median score using NumPy
median_scores = np.median(scores)

# Calculate the standard deviation using NumPy
std_scores = np.std(scores)

# Find the highest score
max_scores = np.max(scores)

# Find the lowest score
min_scores = np.min(scores)

# Display the NumPy statistics
print("\n--- NumPy Stats ---")

print(f"Mean score   : {mean_scores:.2f}")
print(f"Median score : {median_scores:.2f}")
print(f"Std deviation: {std_scores:.2f}")
print(f"Max score    : {max_scores}")
print(f"Min score    : {min_scores}")

# Step 3: Find the category with the most stories

# Count the number of stories in each category
category_count = data["category"].value_counts()

# Find the category with the highest number of stories
most_common_category = category_count.idxmax()

# Find the number of stories in that category
most_common_category_count = category_count.max()

print(
    f"\nMost stories in: "
    f"{most_common_category} "
    f"({most_common_category_count} stories)"
)

# Step 4: Find the most-commented story

# Find the index of the story with the highest number of comments
most_commented_index = data["num_comments"].idxmax()

# Get the complete row of the most-commented story
most_commented_story = data.loc[most_commented_index]

# Display the title and comment count
print(
    f'\nMost commented story: '
    f'"{most_commented_story["title"]}" '
    f'— {most_commented_story["num_comments"]} comments'
)

# Step 5: Add the engagement column

# Engagement measures the number of comments relative to the score +1 is used to avoid division by zero
data["engagement"] = (
    data["num_comments"] / (data["score"] + 1)
)

# Step 6: Add the is_popular column

# A story is considered popular when its score is greater than the average score of all stories
data["is_popular"] = data["score"] > average_score

# Display the newly added columns
print("\nNew columns added:")
print(data[["engagement", "is_popular"]].head())

# Step 7: Save the analysed data

# Path where the analysed CSV will be saved
output_path = (
    "/content/drive/MyDrive/MiniProject1/Data/trends_analysed.csv"
)

# Save the DataFrame as a CSV file
data.to_csv(output_path, index=False)

# Confirm that the file was saved successfully
print(f"\nSaved file with {len(data)} rows")