# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-WHceYtMGenJOMNzsaGfVK1MkuL_Ayd

**TREND PULSE**
"""

import requests #Call hacker news API
import json #Save data as JSON
import os #Create or check data/ folder
import time
from datetime import datetime

"""**TASK - 1**"""

# API URLs
top_stories_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
story_url = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# User-Agent required by the assignment
headers = {
    "User-Agent": "TrendPulse/1.0"
}

# Categories and keywords
categories = {
    "technology": [
        "AI", "software", "tech", "code", "computer",
        "data", "cloud", "API", "GPU", "LLM"
    ],

    "worldnews": [
        "war", "government", "country", "president",
        "election", "climate", "attack", "global"
    ],

    "sports": [
    "NFL", "NBA", "FIFA", "sport", "game",
    "team", "player", "league", "championship"
    ],

    "science": [
    "research", "study", "space", "physics",
    "biology", "discovery", "NASA", "genome"
    ],

    "entertainment": [
        "movie", "film", "music", "Netflix", "game",
        "book", "show", "award", "streaming"
    ]
}

# Function to check whether a title matches a category
def matches_category(title, keywords):
    title = title.lower()
    for keyword in keywords:
        if keyword.lower() in title:
            return True
    return False

# STEP 1: Fetch the first 500 top story IDs
response = requests.get(
    top_stories_url,
    headers=headers
)
if response.status_code != 200:
    print("Failed to fetch top story IDs.")
else:
    story_ids = response.json()[:500]
    print("Number of story IDs:", len(story_ids))

    # STEP 2: Fetch details of the 500 stories
    fetched_stories = []
    for story_id in story_ids:
        url = story_url.format(story_id)
        response = requests.get(
            url,
            headers=headers
        )
        # If request fails, print message and continue
        if response.status_code != 200:
            print(f"Failed to fetch story {story_id}")
            continue
        story = response.json()
        # Ignore empty responses
        if not story:
            continue
        fetched_stories.append(story)

    print("Stories successfully fetched:", len(fetched_stories))

    # STEP 3: Collect up to 25 stories per category
    collected_stories = []

    category_counts = {
        "technology": 0,
        "worldnews": 0,
        "sports": 0,
        "science": 0,
        "entertainment": 0
    }

    # Process each category separately
    for category, keywords in categories.items():
        print(f"\nCollecting {category} stories...")
        for story in fetched_stories:
            # Stop when this category reaches 25 stories
            if category_counts[category] >= 25:
                break
            title = story.get("title", "")
            # Check whether the title matches this category
            if not matches_category(title, keywords):
                continue
            # Extract the required fields
            story_data = {
                "post_id": story.get("id"),
                "title": story.get("title"),
                "category": category,
                "score": story.get("score", 0),
                "num_comments": story.get("descendants", 0),
                "author": story.get("by"),
                "collected_at": datetime.now().isoformat()
            }
            # Add story to the final collection
            collected_stories.append(story_data)
            category_counts[category] += 1
        print(
            f"{category}: "
            f"{category_counts[category]} stories collected"
        )
        # Wait 2 seconds between category loops
        time.sleep(2)

    # STEP 4: Create data folder
    os.makedirs("data", exist_ok=True)

    # STEP 5: Create output filename
    date_string = datetime.now().strftime("%Y%m%d")
    filename = f"data/trends_{date_string}.json"

    # STEP 6: Save data as JSON
    with open(filename, "w", encoding="utf-8") as file:
        json.dump(
            collected_stories,
            file,
            indent=4
        )

    # STEP 7: Print final results
    print("\nFinal category counts:")
    for category, count in category_counts.items():
        print(f"{category}: {count}")
    print(f"\nCollected {len(collected_stories)} stories.")
    print(f"Saved to {filename}")